
# ---------------------------------------------------------------------------
# MtbPython.py
# Created on: Wed Sep 02 2009 08:29:09 PM
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# Used to locate potential Mountain Biking trail locations 
# ---------------------------------------------------------------------------

# Import system modules
#IMPORT IS A KEYWORD
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
#gp = arcgisscripting.create() IS AN ASSIGNMENT STATEMENT
gp = arcgisscripting.create()

# Load required toolboxes...
# Load required toolboxes... IS A COMMENT
gp.AddToolbox("F:/NR_533/ESRI_Data/VirtualCampus/Geoprocess/Prepare/LynxProject/Tools/LynxTools_Prepare.tbx")
gp.AddToolbox("C:/Documents and Settings/Administrator/Application Data/ESRI/ArcToolbox/My Toolboxes/MTB.tbx")

# Set the Geoprocessing environment...
#GP.SCRATCHWORKSPACE IS A VARIABLE
#"F:\\NR_533\\Model Builder Assignment\\MTBscratch.mdb" IS AN EXTENSION
gp.scratchWorkspace = "F:\\NR_533\\Model Builder Assignment\\MTBscratch.mdb"
gp.workspace = "F:\\NR_533\\Model Builder Assignment\\MTB.mdb"


# Local variables...
# "WakeOpenSpace_Layer" IS A STRING LITERAL
MTBscratch_mdb = "F:\\NR_533\\Model Builder Assignment\\MTBscratch.mdb"
Wake_PublicOpenSpace_2009_07 = "Wake_PublicOpenSpace_2009_07"
WakeOpenSpace = "F:\\NR_533\\Model Builder Assignment\\MTBscratch.mdb\\WakeOpenSpace"
WakeOpenSpace_Layer = "WakeOpenSpace_Layer"
Wake_Open_Acre = "WakeOpenSpace_Layer"
Wake_Open_Type = "WakeOpenSpace_Layer"
WakeOpenSpace_Layer__2_ = "WakeOpenSpace_Layer"
Acre_Dissolve = "F:\\NR_533\\Model Builder Assignment\\MTBscratch.mdb\\WakeOpenSpace_Dissolve"
Type_Dissolve = "F:\\NR_533\\Model Builder Assignment\\MTBscratch.mdb\\WakeOpenSpace_Dissolve1"
MTB_Trail_Possibilities = "F:\\NR_533\\Model Builder Assignment\\MTBscratch.mdb\\WakeOpenSpace_Dissolve_Merge"
WakeOpenSpace_Layer__3_ = "WakeOpenSpace_Layer"
Clip_Final = "F:\\NR_533\\Model Builder Assignment\\MTBscratch.mdb\\Clip_Final"
Contour_020 = "Contour_020"

# Process: Feature Class to Feature Class (3)...
# Feature Class to Feature Class (3)... IS A SUBROUTINE
gp.toolbox = "C:/Documents and Settings/Administrator/Application Data/ESRI/ArcToolbox/My Toolboxes/MTB.tbx"
gp.FeatureClassToFeatureClass(Wake_PublicOpenSpace_2009_07, MTBscratch_mdb, "WakeOpenSpace", "", "NAME NAME true true false 35 Text 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,NAME,-1,-1;ACRES ACRES true true false 8 Double 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,ACRES,-1,-1;OWNER OWNER true true false 35 Text 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,OWNER,-1,-1;JURISDICTI JURISDICTI true true false 25 Text 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,JURISDICTI,-1,-1;TYPE TYPE true true false 20 Text 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,TYPE,-1,-1;MANAGER MANAGER true true false 40 Text 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,MANAGER,-1,-1;COMMENTS COMMENTS true true false 50 Text 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,COMMENTS,-1,-1;BLDGCODE BLDGCODE true true false 10 Text 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,BLDGCODE,-1,-1;SHAPE_Leng SHAPE_Leng true true false 8 Double 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,SHAPE_Leng,-1,-1;CORRIDOR CORRIDOR true true false 50 Text 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,CORRIDOR,-1,-1;OS_Number OS_Number true true false 50 Text 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,OS_Number,-1,-1;Shape_Length Shape_Length false true true 8 Double 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,Shape_Length,-1,-1;Shape_Area Shape_Area false true true 8 Double 0 0 ,First,#,F:\\NR_533\\Model Builder Assignment\\MTB.mdb\\Wake_PublicOpenSpace_2009_07,Shape_Area,-1,-1", "")

# Process: Make Feature Layer...
gp.toolbox = "C:/Documents and Settings/Administrator/Application Data/ESRI/ArcToolbox/My Toolboxes/MTB.tbx"
gp.MakeFeatureLayer(WakeOpenSpace, WakeOpenSpace_Layer, "", "", "NAME NAME VISIBLE;ACRES ACRES VISIBLE;OWNER OWNER VISIBLE;JURISDICTI JURISDICTI VISIBLE;TYPE TYPE VISIBLE;MANAGER MANAGER VISIBLE;COMMENTS COMMENTS VISIBLE;BLDGCODE BLDGCODE VISIBLE;SHAPE_Leng SHAPE_Leng VISIBLE;CORRIDOR CORRIDOR VISIBLE;OS_Number OS_Number VISIBLE")

# Process: Select Layer By Attribute...
gp.toolbox = "C:/Documents and Settings/Administrator/Application Data/ESRI/ArcToolbox/My Toolboxes/MTB.tbx"
gp.SelectLayerByAttribute(WakeOpenSpace_Layer, "NEW_SELECTION", "ACRES >=20")

# Process: Add Field...
gp.toolbox = "C:/Documents and Settings/Administrator/Application Data/ESRI/ArcToolbox/My Toolboxes/MTB.tbx"
gp.AddField(Wake_Open_Acre, "WakeAcre", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Dissolve...
gp.toolbox = "C:/Documents and Settings/Administrator/Application Data/ESRI/ArcToolbox/My Toolboxes/MTB.tbx"
gp.Dissolve(WakeOpenSpace_Layer__3_, Acre_Dissolve, "", "", "MULTI_PART")

# Process: Select Layer By Attribute (2)...
gp.toolbox = "C:/Documents and Settings/Administrator/Application Data/ESRI/ArcToolbox/My Toolboxes/MTB.tbx"
gp.SelectLayerByAttribute(WakeOpenSpace_Layer, "NEW_SELECTION", "[TYPE] = 'OPEN SPACE' OR [TYPE] = 'PARK'")

# Process: Add Field (2)...
gp.toolbox = "C:/Documents and Settings/Administrator/Application Data/ESRI/ArcToolbox/My Toolboxes/MTB.tbx"
gp.AddField(Wake_Open_Type, "Open_Park", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Dissolve (2)...
gp.toolbox = "C:/Documents and Settings/Administrator/Application Data/ESRI/ArcToolbox/My Toolboxes/MTB.tbx"
gp.Dissolve(WakeOpenSpace_Layer__2_, Type_Dissolve, "", "", "MULTI_PART")

# Process: Merge...
gp.toolbox = "C:/Documents and Settings/Administrator/Application Data/ESRI/ArcToolbox/My Toolboxes/MTB.tbx"
gp.Merge("'F:\\NR_533\\Model Builder Assignment\\MTBscratch.mdb\\WakeOpenSpace_Dissolve';'F:\\NR_533\\Model Builder Assignment\\MTBscratch.mdb\\WakeOpenSpace_Dissolve1'", MTB_Trail_Possibilities, "")

# Process: Clip (2)...
gp.toolbox = "F:/NR_533/ESRI_Data/VirtualCampus/Geoprocess/Prepare/LynxProject/Tools/LynxTools_Prepare.tbx"
gp.Clip(Contour_020, MTB_Trail_Possibilities, Clip_Final, "")